---
sudo: false
language: ruby
rvm:
  - 2.7
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # quicker html-proofer install
